apiVersion: v1
kind: ConfigMap
metadata:
  name: DB-conf
data:
  MYSQL_ROOT_PASSWORD : "root"
  MYSQL_ALLOW_EMPTY_PASSWORD : "true"
  MYSQL_USER : "petclinic"
  MYSQL_PASSWORD : "petclinic"
  MYSQL_DATABASE : "petclinic"